name: ${name}
version: ${version}
api-version: 1.13
description: ${description}
author: ${author}
website: ${url}

main: ${mainClass}

commands:
  bookmarks:
    description: Gives the bookmark book
    usage: /bookmark or /bm
    aliases: [bm,bookmark,ecbmc]
permissions: {}